name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout your code
      - name: Checkout repository
        uses: actions/checkout@v4                             # :contentReference[oaicite:1]{index=1}

      # 2. Install uv
      - name: Install uv
        uses: astral-sh/setup-uv@v5                            # :contentReference[oaicite:2]{index=2}
        with:
          enable-cache: true

      # 3. Set up Python (either via uv or GitHub action)
      - name: Set up Python
        run: uv python install                                 # :contentReference[oaicite:3]{index=3}
        # OR, if you prefer GitHub's caching:
        # uses: actions/setup-python@v5
        # with: python-version-file: "pyproject.toml"           # :contentReference[oaicite:4]{index=4}

      # 4. Sync dependencies
      - name: Install dependencies
        run: |
          uv pip sync --system                                 # :contentReference[oaicite:5]{index=5}

      # 5. Lint & format check with Ruff
      - name: Lint & format with Ruff
        uses: chartboost/ruff-action@v1                        # :contentReference[oaicite:6]{index=6}
        with:
          args: check .

      # 6. Static type checking with mypy
      - name: Type-check with mypy
        uses: sasanquaneuf/mypy-github-action@releases/v1      # :contentReference[oaicite:7]{index=7}

      # 7. Run tests with pytest
      - name: Run tests
        run: uv run --frozen pytest                            # :contentReference[oaicite:8]{index=8}
