name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Install uv
      run: pip install uv
    
    - name: Install your package + runtime deps
      run: |
        python -m pip install --upgrade pip
        pip install .
      
    - name: Install test dependencies
      run: pip install pytest jsonlines freezegun
    
    - name: Run clean
      run: make clean
    
    - name: Install ruff
      run: pip install ruff
    
    - name: Run lint
      run: make lint
    
    - name: Run format
      run: make format
    
    - name: Run test
      run: make test